spring.application.name=StemLinkApp
spring.datasource.url=jdbc:postgresql://localhost:5433/stemlink_db
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=miSecretSuperLargoParaJWTQueDebeTener32Chars
jwt.expiration-access=86400000