spring.application.name=StemLinkApp
spring.datasource.url=jdbc:postgresql://localhost:5435/stemlink_db
spring.datasource.username=user1
spring.datasource.password=password1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=9a4f4c354565456c4a59405b4b5a6b5a415a6b5a415a6b5a415a6b5a415a6b5a
jwt.expiration-access=3600000

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=7eaaa109156b1b
spring.mail.password=3038c6f35b5a61
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true